{{- if (default true .Values.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "three-tier-app.fullname" . }}
  namespace: {{ .Values.namespace }}
{{- end }}

