apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-test-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "my-image=396608791503.dkr.ecr.us-east-1.amazonaws.com/my-test-app"
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/my-image.update-strategy: "name"
    argocd-image-updater.argoproj.io/my-image.tag-pattern: "^qa1\\..*"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Akshaya-Parthi/argocd-image-updater.git
    targetRevision: main
    path: my-app-chart
    helm:
      parameters:
        - name: "replicaCount"
          value: "2"
        - name: "image.repository"
          value: "396608791503.dkr.ecr.us-east-1.amazonaws.com/my-test-app"
        - name: "image.tag"
          value: qa1.26092024
  destination:
    server: https://kubernetes.default.svc
    namespace: qa1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true