helm:
  parameters:
  - name: image.repository
    value: 396608791503.dkr.ecr.us-east-1.amazonaws.com/dev2
    forcestring: false
  - name: image.tag
    value: v5.0.0
    forcestring: true
  - name: replicaCount
    value: "1"
    forcestring: false
  - name: image.name
    value: 396608791503.dkr.ecr.us-east-1.amazonaws.com/dev2
    forcestring: true
